package com.LibraryManage.dao;

import com.LibraryManage.po.LendList;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component("lendListDao")
public interface LendListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int insert(LendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int insertSelective(LendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    LendList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(LendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int updateByPrimaryKey(LendList record);
    //查询借阅记录
    List<LendList> queryLendListAll(LendList lendList);
    //查询当前用户已经借了多少本信息
    int queryLendNumberById(Integer id);
    //删除
    int deleteLendListById(Integer id);
    //还书
    int updateLendListSubmit(LendList lendList);
    //查询时间线
    List<LendList> queryLookBookList(@Param("rid") Integer rid, @Param("bid") Integer bid);


}