package com.LibraryManage.dao;

import com.LibraryManage.po.Notice;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component("noticeDao")
public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int updateByPrimaryKeyWithBLOBs(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Fri Jan 29 23:28:51 GMT+08:00 2021
     */
    int updateByPrimaryKey(Notice record);
    //查询公告信息
    List<Notice> queryNoticeAll(@Param("content") String content);
    //公告删除
    void deleteNoticeByIds(List<Integer> id);
    //查询详细根据id查询
    Notice queryNoticeById(Integer id);
}